backend:
  name: 'test-repo'

media_folder: 'assets'

collections:
  - name: post
    label: Post
    folder: _posts
    create: true
    fields:
      - name: title
        label: Title
        widget: string

      - name: content
        label: Content
        widget: markdown